name: prohealth360_daktari
version: 1.0.0
description: ProHealth360 Daktari Application
repository: https://github.com/savannahghi/AfyaMoja.git
issue_tracker: https://github.com/savannahghi/AfyaMoja/issues
documentation: https://github.com/savannahghi/AfyaMoja/tree/main/docs
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  afya_moja_core: ^0.2.5
  app_wrapper: ^0.1.36
  async_redux: ^15.0.0
  collection: ^1.16.0
  connectivity_plus: ^2.3.5
  cupertino_icons: ^1.0.5
  debug_logger: ^0.0.23
  dotted_decoration: ^2.0.0
  firebase_analytics: ^9.1.12
  firebase_core: ^1.19.1
  firebase_messaging: ^11.4.4
  flutter:
    sdk: flutter
  flutter_config: ^2.0.0
  flutter_graphql_client: ^0.1.23
  flutter_html: ^3.0.0-alpha.5
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: ^1.2.1
  flutter_svg: ^1.0.3
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  path: ^1.8.0
  quiver: ^3.1.0
  rxdart: ^0.27.4
  sentry_flutter: ^6.6.1
  shared_themes: ^0.1.1
  sms_autofill: ^2.2.0
  sqflite: ^2.0.2+1
  stream_chat_flutter: ^4.1.0
  unicons: ^2.0.1
  url_launcher: ^6.1.4

dev_dependencies:
  build_runner: ^2.1.11
  built_value_generator: ^8.3.3
  connectivity_plus_platform_interface: ^1.2.1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  lint: ^1.8.2
  mockito: ^5.2.0
  mocktail_image_network: ^0.3.1
  plugin_platform_interface: ^2.1.2

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - assets/
    - assets/images/
    - assets/icons/
