name: healthcloud
version: 1.0.0
description: AfyaMoja Caregivers' Application
repository: https://github.com/savannahghi/AfyaMoja.git
issue_tracker: https://github.com/savannahghi/AfyaMoja/issues
documentation: https://github.com/savannahghi/AfyaMoja/tree/main/docs
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  afya_moja_core: ^0.0.34
  app_wrapper: ^0.1.32
  async_redux: ^12.0.0
  cupertino_icons: ^1.0.3
  dart_fcm: ^0.0.24
  debug_logger: ^0.0.23
  domain_objects: ^0.0.31-nullsafety
  dotted_decoration: ^2.0.0
  firebase_analytics: ^8.3.3
  firebase_core: ^1.7.0
  firebase_core_platform_interface: ^4.0.1
  firebase_crashlytics: ^2.2.3
  flutter:
    sdk: flutter
  flutter_config: ^2.0.0
  flutter_graphql_client: ^0.1.23
  flutter_svg: ^0.22.0
  freezed: ^0.14.2
  freezed_annotation: ^0.14.2
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.0.1
  json_serializable: ^4.1.3
  misc_utilities: ^0.1.27-nullsafety
  path: ^1.8.0
  quiver: ^3.0.1
  rxdart: ^0.27.2
  sentry_flutter: ^5.1.0
  shared_themes: ^0.1.1
  shared_ui_components: ^0.1.46-nullsafety
  sqflite: ^2.0.0+4
  user_feed: ^0.1.45-nullsafety
  user_profile: ^0.1.24-nullsafety

dev_dependencies:
  build_runner: ^2.0.4
  built_value_generator: ^8.0.2
  connectivity_platform_interface: ^2.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  lint: ^1.6.0
  mockito: ^5.0.1
  mocktail_image_network: ^0.1.0
  test: ^1.16.5

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - assets/
    - assets/images/
    - assets/icons/
