name: healthcloud
version: 1.0.0
description: AfyaMoja Caregivers' Application
repository: https://github.com/savannahghi/AfyaMoja.git
issue_tracker: https://github.com/savannahghi/AfyaMoja/issues
documentation: https://github.com/savannahghi/AfyaMoja/tree/main/docs
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  bewell_pro_core: ^1.1.16-nullsafety
  cupertino_icons: ^1.0.3
  domain_objects: ^0.0.27-nullsafety
  flutter:
    sdk: flutter
  flutter_graphql_client: ^0.1.23
  freezed: ^0.14.2
  freezed_annotation: ^0.14.2
  json_annotation: ^4.0.1
  json_serializable: ^4.1.3
  misc_utilities: ^0.1.27-nullsafety
  quiver: ^3.0.1
  sentry_flutter: ^5.1.0

dev_dependencies:
  build_runner: ^2.0.4
  built_value_generator: ^8.0.2
  connectivity_platform_interface: ^2.0.0
  flutter_config: ^2.0.0
  flutter_test:
    sdk: flutter
  lint: ^1.6.0
  mockito: ^5.0.1
  mocktail_image_network: ^0.1.0
  test: ^1.16.5

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - assets/
    - assets/images/
    - assets/icons/
